<nav class="woocommerce-breadcrumb">
<a href="<?php echo site_url(); ?>">Home</a>
 /
<a href="<?php echo site_url(); ?>/medical-equipment/">Medical Equipment</a>
 /
<a href="<?php echo site_url(); ?>/imaging-parts/">Imaging Parts</a>
 / Imaging Parts A-L
</nav>

<div class="container header-wrap-text-medical-equipment">
<h2 class="header-wrap-text-medical-equipment-header">Imaging Parts A-L</h2>
We service the following manufacturers AccuSync, AKG Acoustics, Asante, Biodex Medical System, Black Box Network Services, Capintec INC, Condonics, CONMED, CTI PET Systems, CPS, Dell, EAO, Eizo Monitors, EPCOS, ebm-papst Inc., Globalstor, Hengstler, Hofmann, Honeywell, HP, IBM, Ivy, Kraus & Naimer, Lambda, Leoni, Lexmark, Liteon, Ludlum, &amp; LUST. Through this extensive list of medical equipment manufacturers we our able to provide the best imaging parts quality at the lowest market price. These products include reconditioned, refurbished, and new imaging parts.
</div>


<div id="hill-rom-parts-table">
  <div class="hill-rom-parts-row">
    <div class="hill-rom-parts-cell">
       <h4></h4>
    </div>
        <div class="hill-rom-parts-cell">
           <h4>Manufacturer</h4>
        </div>
        <div class="hill-rom-parts-cell">
           <h4>Part Number</h4>
        </div>
        <div class="hill-rom-parts-cell">
           <h4>Description</h4>
        </div>
        <div class="hill-rom-parts-cell">
           <h4>Price</h4>
        </div>
        <div class="hill-rom-parts-cell">
           <h4>Condition</h4>
        </div>
    </div>


<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=3550816&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/accusync-170x150.png" /></div><div class="hill-rom-parts-cell">AccuSync</div><div class="hill-rom-parts-cell">3550816</div><div class="hill-rom-parts-cell">AccuSync 71, ECG Monitor</div><div class="hill-rom-parts-cell">$35,076.00</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=AccuSync-1&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/accusync-170x150.png" /></div><div class="hill-rom-parts-cell">AccuSync</div><div class="hill-rom-parts-cell">AccuSync-1</div><div class="hill-rom-parts-cell">Accusync 7, ECG Monitor</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Untested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=AccuSync-2&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/accusync-170x150.png" /></div><div class="hill-rom-parts-cell">AccuSync</div><div class="hill-rom-parts-cell">AccuSync-2</div><div class="hill-rom-parts-cell">9 Pin ECG Cable</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=BiodexMedicalSystems-1&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Biodex-Medical-Systems-170x150.png" /></div><div class="hill-rom-parts-cell">Biodex Medical Systems</div><div class="hill-rom-parts-cell">BiodexMedicalSystems-1</div><div class="hill-rom-parts-cell">Source Holder for Phantom w/o Wheels</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=BiodexMedicalSystems-2&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Biodex-Medical-Systems-170x150.png" /></div><div class="hill-rom-parts-cell">Biodex Medical Systems</div><div class="hill-rom-parts-cell">BiodexMedicalSystems-2</div><div class="hill-rom-parts-cell">Shield for Lab Purposes</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=BiodexMedicalSystems-3&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Biodex-Medical-Systems-170x150.png" /></div><div class="hill-rom-parts-cell">Biodex Medical Systems</div><div class="hill-rom-parts-cell">BiodexMedicalSystems-3</div><div class="hill-rom-parts-cell">Shielded Syringe Carriers, Small</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=BiodexMedicalSystems-4&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Biodex-Medical-Systems-170x150.png" /></div><div class="hill-rom-parts-cell">Biodex Medical Systems</div><div class="hill-rom-parts-cell">BiodexMedicalSystems-4</div><div class="hill-rom-parts-cell">Shielded Syringe Carriers, Large</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=BiodexMedicalSystems-5&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Biodex-Medical-Systems-170x150.png" /></div><div class="hill-rom-parts-cell">Biodex Medical Systems</div><div class="hill-rom-parts-cell">BiodexMedicalSystems-5</div><div class="hill-rom-parts-cell">Atomlab 300 Dose Calibrator</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=Capintec-1&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Capintec-170x150.png" /></div><div class="hill-rom-parts-cell">Capintec, INC</div><div class="hill-rom-parts-cell">Capintec-1</div><div class="hill-rom-parts-cell">Capintec Wipe Test Counter</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=Capintec-2&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Capintec-170x150.png" /></div><div class="hill-rom-parts-cell">Capintec, INC</div><div class="hill-rom-parts-cell">Capintec-2</div><div class="hill-rom-parts-cell">Shield for Lab Purposes</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=Condonics-1&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/condonics-170x150.png" /></div><div class="hill-rom-parts-cell">Condonics</div><div class="hill-rom-parts-cell">Condonics-1</div><div class="hill-rom-parts-cell">Codonics Horizon Multi-Media Printer</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=Condonics-2&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/condonics-170x150.png" /></div><div class="hill-rom-parts-cell">Condonics</div><div class="hill-rom-parts-cell">Condonics-2</div><div class="hill-rom-parts-cell">Color Roller</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=NP-1600M&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/condonics-170x150.png" /></div><div class="hill-rom-parts-cell">Condonics</div><div class="hill-rom-parts-cell">NP-1600M</div><div class="hill-rom-parts-cell">Codonics NP-1600M Medical Printer</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=FSA24-003R&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Conmed-170x150.png" /></div><div class="hill-rom-parts-cell">Conmed</div><div class="hill-rom-parts-cell">FSA24-003R</div><div class="hill-rom-parts-cell">6 Pin Conmed ECG Cable</div><div class="hill-rom-parts-cell">$34.95</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=FSA24-003R&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Conmed-170x150.png" /></div><div class="hill-rom-parts-cell">Conmed</div><div class="hill-rom-parts-cell">FSA24-003R</div><div class="hill-rom-parts-cell">L/W:SHLD;GRAB,24",3/PKG,3B</div><div class="hill-rom-parts-cell">$34.95</div><div class="hill-rom-parts-cell">Untested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=FSR1311&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Conmed-170x150.png" /></div><div class="hill-rom-parts-cell">Conmed</div><div class="hill-rom-parts-cell">FSR1311</div><div class="hill-rom-parts-cell">3 Lead Cable & 6 Pin Cable</div><div class="hill-rom-parts-cell">$125.50</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=FSR1311&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Conmed-170x150.png" /></div><div class="hill-rom-parts-cell">Conmed</div><div class="hill-rom-parts-cell">FSR1311</div><div class="hill-rom-parts-cell">3 Lead Grapple Cable</div><div class="hill-rom-parts-cell">$125.50</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=1130.1&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Conmed-170x150.png" /></div><div class="hill-rom-parts-cell">Conmed</div><div class="hill-rom-parts-cell">1130.1</div><div class="hill-rom-parts-cell">REUSE 3X60MM INTRODUCER CD1530</div><div class="hill-rom-parts-cell">$246.52</div><div class="hill-rom-parts-cell">Untested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=Conmed-1&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Conmed-170x150.png" /></div><div class="hill-rom-parts-cell">Conmed</div><div class="hill-rom-parts-cell">Conmed-1</div><div class="hill-rom-parts-cell">6 Pin ECG Cable for (ACCUSYNC 72)</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=Dell-1&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Dell_Logo-170x150.png" /></div><div class="hill-rom-parts-cell">Dell</div><div class="hill-rom-parts-cell">Dell-1</div><div class="hill-rom-parts-cell">Keyboard</div><div class="hill-rom-parts-cell">$22.95</div><div class="hill-rom-parts-cell">Untested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=Dell-2&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Dell_Logo-170x150.png" /></div><div class="hill-rom-parts-cell">Dell</div><div class="hill-rom-parts-cell">Dell-2</div><div class="hill-rom-parts-cell">19" DELL LCD Monitor, Black</div><div class="hill-rom-parts-cell">$217.99</div><div class="hill-rom-parts-cell">Untested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=11301&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Dell_Logo-170x150.png" /></div><div class="hill-rom-parts-cell">Dell</div><div class="hill-rom-parts-cell">11301</div><div class="hill-rom-parts-cell">18" Monitor</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=8077534&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Globalstor-170x150.png" /></div><div class="hill-rom-parts-cell">Globalstor</div><div class="hill-rom-parts-cell">8077534</div><div class="hill-rom-parts-cell">MO Tape Drive, ECAT- Exchange</div><div class="hill-rom-parts-cell">$3,338.00</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=8077534&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Globalstor-170x150.png" /></div><div class="hill-rom-parts-cell">Globalstor</div><div class="hill-rom-parts-cell">8077534</div><div class="hill-rom-parts-cell">MO Tape Drive, ECAT</div><div class="hill-rom-parts-cell">$8,321.00</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=8727187&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Globalstor-170x150.png" /></div><div class="hill-rom-parts-cell">Globalstor</div><div class="hill-rom-parts-cell">8727187</div><div class="hill-rom-parts-cell">MO Disk Drive, ECAT- Exchange</div><div class="hill-rom-parts-cell">$12,080.00</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=8727187&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Globalstor-170x150.png" /></div><div class="hill-rom-parts-cell">Globalstor</div><div class="hill-rom-parts-cell">8727187</div><div class="hill-rom-parts-cell">MO Disk Drive, ECAT</div><div class="hill-rom-parts-cell">$20,924.00</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=Honeywell-1&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Honeywell-170x150.png" /></div><div class="hill-rom-parts-cell">Honeywell</div><div class="hill-rom-parts-cell">Honeywell-1</div><div class="hill-rom-parts-cell">Controls</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Untested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=Honeywell-2&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Honeywell-170x150.png" /></div><div class="hill-rom-parts-cell">Honeywell</div><div class="hill-rom-parts-cell">Honeywell-2</div><div class="hill-rom-parts-cell">Honeywell Series 2000 Electronic Temperature Controller Kit</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=Honeywell-3&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Honeywell-170x150.png" /></div><div class="hill-rom-parts-cell">Honeywell</div><div class="hill-rom-parts-cell">Honeywell-3</div><div class="hill-rom-parts-cell">Honeywell Kit with 3 Sensors & 2 Control Panels</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=HP-1&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/HP-170x150.png" /></div><div class="hill-rom-parts-cell">HP</div><div class="hill-rom-parts-cell">HP-1</div><div class="hill-rom-parts-cell">SUN Blade 2000 PGX-64 Video Card</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Untested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=IBM-1&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/IBM-170x150.png" /></div><div class="hill-rom-parts-cell">IBM</div><div class="hill-rom-parts-cell">IBM-1</div><div class="hill-rom-parts-cell">Keyboard</div><div class="hill-rom-parts-cell">$83.00</div><div class="hill-rom-parts-cell">Untested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=10151205&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Lexmark-170x150.png" /></div><div class="hill-rom-parts-cell">Lexmark</div><div class="hill-rom-parts-cell">10151205</div><div class="hill-rom-parts-cell">Lexmark Laser Printer, Black</div><div class="hill-rom-parts-cell">$4,345.00</div><div class="hill-rom-parts-cell">Tested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=Lexmark-1&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/Lexmark-170x150.png" /></div><div class="hill-rom-parts-cell">Lexmark</div><div class="hill-rom-parts-cell">Lexmark-1</div><div class="hill-rom-parts-cell">Lexmark Laser Printer, Black and Silver</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Untested</div></a>
<a class="hill-rom-parts-row" target="_blank" href="<?php echo site_url(); ?>/?s=LUDLUM-1&amp;post_type=product"><div class="hill-rom-parts-cell"><img src="<?php echo site_url(); ?>/wp-content/uploads/2016/05/ludlum_logo-170x150.png" /></div><div class="hill-rom-parts-cell">LUDLUM</div><div class="hill-rom-parts-cell">LUDLUM-1</div><div class="hill-rom-parts-cell">Gamma Radiation Detector</div><div class="hill-rom-parts-cell">Request A Quote</div><div class="hill-rom-parts-cell">Tested</div></a>


</div>   <br /><br />
